### PR TITLE
rework

### PR DESCRIPTION
**Pull request by kumarabd**
Signed-off-by: kumarabd <abishekkumar92@gmail.com>

**Description**

- dynamic discovery based on input resource config
- dynamic informers based on input resource config

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by kumarabd** [comment]
depends on https://github.com/layer5io/meshkit/pull/32

**Comment by leecalcote** [comment]
I understand that MeshSync was failing, but why the rewrite?

**Comment by leecalcote** [comment]
Fixes #37 and... #36?

**Comment by kumarabd** [comment]
> I understand that MeshSync was failing, but why the rewrite?

Because 
- the update events had bugs
- Reconnect logic on nats was broken
- Too much code effort for small changes
- Better Object model support.
Spending hours debugging seemed worthless

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
A lint check or two to look after...

**Comment by kumarabd** [comment]
> A lint check or two to look after...

Because meshkit version wasn't available, it is now.

**Pull request merged**
