### PR TITLE
Add golangci-lint

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: aisuko <urakiny@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Aisuko** [comment]
I'd like to release the latest stable version of `meshsync` after this PR was merged

**Review by leecalcote — COMMENTED** [review]
Thank you, @Aisuko 💪

**Comment by leecalcote** [comment]
@Aisuko this workflow is experiencing a failure - https://github.com/layer5io/meshsync/actions/runs/459374743

**Comment by Aisuko** [comment]
> @Aisuko this workflow is experiencing a failure - https://github.com/layer5io/meshsync/actions/runs/459374743

Good, I saw the ` Error: SA5008: unknown JSON option "startedat" (staticcheck)` with the code, and we ned to fix the issue.

**Comment by Aisuko** [comment]
Hi @kumarabd, there may need your help. Could we remove the `startedat` in https://github.com/layer5io/meshsync/blob/6185522c16b6a6c2e49aa920fa7288ad5e135399/api/grpc/grpc.go#L22, or find other solutions?

**Comment by kumarabd** [comment]
@Aisuko remove the `string` from the json tag and you won't get any issues. The tag has to be just `json:"startedat"`

**Pull request merged**
